nodeLinker: pnp

packageExtensions:
  next-pwa@*:
    dependencies:
      webpack: "*"
      "@babel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  cpu:
    - x86
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.2.1.cjs
